### ISSUE TITLE
Module not found

### ISSUE THREAD

**Issue by Phoenix-Game** [Archasion/bug-tracker#14]
When I try to start the bot using npm start run I get the error that module Client.js cannot be found.
I'm using Ubuntu 20.04.5 LTS, npm version 9.4.0
![Screenshot from 2023-02-01 15-34-26](https://user-images.githubusercontent.com/65184791/216089315-aeffe0fa-2057-4f63-b399-e6ab4427b87e.png)

**Comment by Archasion** [comment]
The documentation has been corrected, run `npm run build; npm run start`
